### ISSUE TITLE
This figure could potentially label the fortnights table as c. You could also reference the figure in the text

### ISSUE THREAD

**Issue by srkobakian** [Sayani07/thesis-SG#5]
https://github.com/Sayani07/thesis-SG/blob/ed8dedfbb1949592c759710ec6260e098f8bcb7e/Rmd/02-gravitas.Rmd#L136

**Comment by Sayani07** [comment]
It is not three different messages, (a) defines linear, and weeks and fortnights represent same class of representation in (b). So keeping it like this.
